### ISSUE TITLE
Setting Z.add, Z.mul, etc as Opaque break the tactics

### ISSUE THREAD

**Issue by Armael** [thery/PolTac#3]
This is not very surprising, but setting Z.add or other operators to Opaque breaks PolTac (because it breaks tactics in poltac such as `Zsimpl := simpl Z Zplus Zmult Zopp ...`).

I'm not sure what is the proper way of fixing this. 
If there was a way of ensuring that these identifiers are transparent *locally*, that would be a solution, but I don't think it's possible currently.
An other solution I see is rewriting `Zsimpl` and other to use rewriting with the right lemmas instead of simpl.

**Comment by thery** [comment]
@Armael  Obviously I wonder why you need Z.add to be opaque but I will not ask the question :wink: 
The problem when you do Opaque Z.add is that you loose computation for constants
Eval compute (0 + 1)%Z returns (0 + 1)%Z
and so has we need to test equality to zero and one, it does not work.

There is a solution (but it is an horrible hack) vm_compute does use the transparency info
so 
Eval vm_compute (0 + 1)%Z returns (1)%Z

So I made a branch opaque that seems to work. Can you try it on your test case

**Comment by Armael** [comment]
> Obviously I wonder why you need Z.add to be opaque but I will not ask the question

Yeah.. that comes from a not-so-good decision from a library I use, which was trying to avoid expanding `2 * x` into a pattern matching when calling `simpl`. But I'm now aware of `Arguments .. : simpl nomatch` and `Arguments .. : simpl never`, so uses of `Opaque` could be removed from the library I think.

> So I made a branch opaque that seems to work. Can you try it on your test case

Thanks, that was fast! I just tested the branch, and it seems to work in my case. Nice! (I just had to put back the `Open Scope Z_scope` in Zex.v otherwise it does not build)

I think if you can stand the vm_compute hack, then it will be useful for me to have it; otherwise, it is not a big deal, and I'll go fix the library that declares Z.add and others as Opaque.

**Comment by thery** [comment]
I think you should do it , anyway I've put the vm_compute stuff in the main branch

**Comment by Armael** [comment]
Thanks!
